config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index create new show] do
    resources :doses, only: %i[create new]
  end
  resources :doses, only: %i[destroy]

  delete '/cocktails/:id', to: 'cocktails#destroy', as: :cocktail_delete

  resources :ingredients, only: %i[index]

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :ingredient, presence: true

  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # before_action :set_cocktail, only: %i[show]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path(@cocktail)
  end

  private

  # def set_cocktail
  # @cocktail = Cocktail.find(params[:id])
  # end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: %i[new create]


  def new
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_dose
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="nav-bar">
    <h1>Cocktails'Arts</h1>
    <p><i class="fas fa-bars"></i></p>
</div>

<div class="banner">
  <h1>Art of Cocktails</h1>
  <p>The best cocktail for you and only you.</p>
  <%= link_to 'Create a new cocktail', new_cocktail_path, class: "btn-gradient" %>
</div>

<div class="test">
  <ul>
    <% @cocktails.each do |cocktail| %>
      <li>
        <div class="card-product">
          <div class="card-product-infos">
            <h2><%= link_to cocktail.name, cocktail_path(cocktail), class: "btn-gradient" %></h2>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

</div>

app/views/cocktails/new.html.erb
<h1>Create your cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "Mojito" %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="nav-bar">
  <h1>Cocktails'Arts</h1>

  <i><i class="fas fa-bars"></i></i>
</div>

<div class="banner-cocktail">
  <h2>Cocktail name : <%= @cocktail.name %></h2>
</div>

<div class="ingredients-list">
  <p>Ingredients List</p>
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.ingredient.name %> : <%= dose.description %> -- <%= link_to dose_path(dose),
        method: 'delete',
        data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    <%end%>
  </ul>
</div>

<%= link_to 'Cocktail List', cocktails_path %>
<br>
<%= link_to 'Create a new dose', new_cocktail_dose_path(@cocktail) %>
<br>
<%= link_to 'delete', cocktail_delete_path, :method => :delete, data: { confirm: "Are you sure?" } %>

app/views/doses/new.html.erb
<h1>Create your dose </h1>
<h2>Let's add a dose to your cocktail</h2>

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description, placeholder: "25cl"%>
  <%= f.submit %>
<% end %>

app/views/ingredients/index.html.erb
<h1>List of all ingredients</h1>

<ul>
  <% @ingredients.each do |ingredient| %>
  <li>id: <%= ingredient.id %> - <%= ingredient.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>